[package]
name = "secret_env"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
aws-config = "0.55.1"
aws-sdk-secretsmanager = "0.27.0"
itertools = "0.10.5"
serde_json = "1.0.96"
